version: 3

services:
  postgresql-db:
    image: postgres:12-alpine
    container_name:
    restart: always
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - ./scripts/postgresql:/etc/mysql/conf.d
    environment:
      - POSTGRESQL_USER=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  



networks:
  default:





    version: '3.1'

    services:
      goacs-db:
        image: mariadb:10.4
        container_name: goacs-db
        restart: always
        volumes:
          - goacs-database-file:/var/lib/mysql
          - ./contrib/database:/docker-entrypoint-initdb.d
          - ./contrib/conf:/etc/mysql/conf.d
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
          - ${MYSQL_PORT}:3306
        ulimits:
          nofile:
            soft: 65536
            hard: 65536
    
      # MongoDB: https://hub.docker.com/_/mongo/
      mongo:
        image: mongo:3
      # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
        environment:
          - http.host=0.0.0.0
          - transport.host=localhost
          - network.host=0.0.0.0
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
      # Graylog: https://hub.docker.com/r/graylog/graylog/
      graylog:
        image: graylog/graylog:3.3
        environment:
          # CHANGE ME (must be at least 16 characters)!
          - GRAYLOG_PASSWORD_SECRET=somepasswordpepper4232342
          # Password: admin
          - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
          - GRAYLOG_HTTP_EXTERNAL_URI=http://api.mms.test:9000/
    
        depends_on:
          - mongo
          - elasticsearch
        ports:
          # Graylog web interface and REST API
          - 9000:9000
          # Syslog TCP
          - 1514:1514
          # Syslog UDP
          - 1514:1514/udp
          # GELF TCP
          - 12201:12201
          # GELF UDP
          - 12201:12201/udp
    
    networks:
      default:
    
    volumes:
      goacs-database-file:
        driver: local